import type { AppConfig } from "./config.js";

export function createTestConfig(
  overrides: Partial<AppConfig> = {},
): AppConfig {
  return {
    appEnv: "test",
    host: "127.0.0.1",
    port: 0,
    publicOrigin: "http://127.0.0.1",
    trustProxyHops: 0,
    databasePath: ":memory:",
    databaseBusyTimeoutMs: 50,
    seedDemoData: true,
    researchProvider: "demo",
    aiProvider: "gateway",
    aiModel: "openai/gpt-5.6-terra",
    openAiBaseUrl: "https://api.openai.com/v1",
    aiReasoningEffort: "xhigh",
    aiDisableResponseStorage: true,
    marketLocationCode: 2840,
    marketLanguageCode: "en",
    marketCountryCode: "US",
    researchMarkets: [
      {
        countryCode: "US",
        locationCode: 2840,
        keywordLanguageCode: "en",
        searchLanguageCode: "en",
      },
    ],
    collectWebCompetitors: false,
    collectAppleMarket: false,
    researchFreshnessDays: 7,
    researchRateLimitPerHour: 30,
    requestRateLimitPerMinute: 1_000,
    loginRateLimitPer15Minutes: 10,
    providerRequestTimeoutMs: 1_000,
    providerMaxRetries: 0,
    maxAiRunsPerDay: 30,
    maxDataForSeoTasksPerDay: 100,
    maxDataForSeoCostPerDayUsd: 0.5,
    maxDataForSeoDiscoveryCostPerDayUsd: 0.05,
    maxDataForSeoCostPerMonthUsd: 10,
    dataForSeoBatchPollIntervalMs: 1,
    dataForSeoBatchTimeoutMs: 100,
    autoDiscoveryEnabled: false,
    discoveryLabsLimit: 100,
    discoverySerpQueriesPerMarket: 8,
    discoveryAppDepth: 100,
    discoveryMaxCandidatesPerRun: 5,
    discoveryAiSignalLimit: 120,
    authRequired: false,
    sessionTtlHours: 24,
    schedulerEnabled: false,
    schedulerPollIntervalMs: 60_000,
    schedulerDiscoveryHour: 3,
    schedulerResearchHour: 3,
    schedulerBackupHour: 2,
    backupDirectory: "./data/test-backups",
    backupRetentionCount: 2,
    ...overrides,
  };
}
